
<!-- 

Find and replace:

- 2 : week number (numeral only)
- 2 : class number (per week, numeral only)
- Friday, January 17, 2025 : date in format Monday, January 1, 2025
- Quarto & Markdown Essentials : brief title/topic of the class meeting

TODO: see if there's a way to make these variables
The problem is that if they are includes with multiple on the index page, the variables would need to process before being included. 

-->

<!--
#### Announcements/Housekeeping/Etc

Text to appear before the accordion

-->

:::::::::::::::::::::::::::::: {#w2c2 .accordion}

:::: accordion-item
::: {.accordion-header .titlebox}
Week 2 | Class 2
:::
::::

:::: accordion-item
::: {.datebox}
Friday, January 17, 2025
:::
::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .prepbox type="button" data-bs-toggle="collapse" data-bs-target="#prep-w2c2" aria-expanded="false" aria-controls="prep-w2c2"}
**Before class:** Markdown, quarto, and yaml readings
:::
::::

:::: {#prep-w2c2 .accordion-collapse .collapse data-bs-parent="#w2c2"}
::: accordion-body
**Readings & Resources:** 

-   Intro2R, [Ch8 Reproducible Reports with R Markdown](https://intro2r.com/rmarkdown_r.html)\*
-   R for Data Science, [ch28: Quarto](https://r4ds.hadley.nz/quarto)\*
-   Quarto Documentation:
    -   [Markdown basics](https://quarto.org/docs/authoring/markdown-basics.html)
    -   Output (YAML options): [PDF](https://quarto.org/docs/output-formats/pdf-basics.html) & [Word](https://quarto.org/docs/output-formats/ms-word.html)
-   Quarto [Getting Started tutorial](https://quarto.org/docs/get-started/hello/rstudio.html)
    -   Note: this tutorial uses the visual editor, which you should not use in this class!
-   [Quarto cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/quarto.pdf)
-   [Quarto for R Markdown Users](https://quarto.org/docs/faq/rmarkdown.html)
-   YAML:
-   Quarto Authoring > > [Front Matter](https://quarto.org/docs/authoring/front-matter.html)
-   [YAML Tutorial](https://yamline.com/tutorial/) (YAMLine)

:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .classbox type="button" data-bs-toggle="collapse" data-bs-target="#class-w2c2" aria-expanded="false" aria-controls="class-w2c2"}
**Class meeting: Markdown & Quarto Fundamentals**
:::
::::

:::: {#class-w2c2 .accordion-collapse .collapse data-bs-parent="#w2c2"}
::: accordion-body
**Materials:**

- [Slides](https://uchicago.box.com/s/8wspb2yhzh5ljswk3q87vk87v2amxj5y)

**Class plans:**

- Lecture: Markdown & Quarto Fundamentals
- Activities
    -   Probably none, but if by some chance we get through the whole lecture with time to spare...
    -   Review the `groceries` notebook from last class
    -   Walk through creating the example `hello_world()` function
        
:::
::::
:::::::


::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .infobox type="button" data-bs-toggle="collapse" data-bs-target="#info-w2c2" aria-expanded="false" aria-controls="info-w2c2"}
**Info:** MLK day; mini-project submissions; timelines
:::
::::

:::: {#info-w2c2 .accordion-collapse .collapse data-bs-parent="#w2c2"}
::: accordion-body
**Reminders:** 

-   No class on Monday, January 20th (MLK Day)
-   When you submit mini-projects, make sure you read the assessment document instructions carefully. Specifically, know when to mark "objective attempt" and "unique objective attempt" in your submission. (You'll never mark "objective met", which is for graders.)

**Additional information:**

-   The no-deadlines-do-what-you-want assessment style of this class is supposed to make it *easier*, not harder, to learn. If you're feeling overwhelmed, please let us know so we can help you get back on track! I suggest coming up with a loose timeline for when you'd like to submit mini-projects and research project drafts throughout the quarter, anticipating changes as we go.
-   Recommendations to get you started:
    -   Submit your first mini-project by the end of Week 3, and plan on 1 every 2 weeks after that
    -   Submit a first (very incomplete!) draft of your research project by the end of Week 4, then additional drafts every 2-3 weeks as needed
        -   Your "draft" can be very, very simple. By the end of Week 4, you should be able to confidently demonstrate some skills across multiple categories -- GitHub, R programming, markdown, and tidyverse, at least! You do not (and probably *should* not) wait to submit your first draft until it has all the components you want in the final project. Treat this as iterative and cumulative work.


:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .todobox type="button" data-bs-toggle="collapse" data-bs-target="#post-2c2" aria-expanded="false" aria-controls="after-w2c2"}
**After class:** Check on repo collaborator invites
:::
::::

:::: {#post-2c2 .accordion-collapse .collapse data-bs-parent="#w2c2"}
::: accordion-body

**To-do:** 

-   Double check that (1) you invited Dr. Dowling and your section's TA to your repo(s) and (2) they accepted the invitation. If we didn't accept, the invite link may have expired and you'll need to re-invite us. 

**Recommended exercises:** View slides for additional details for each exercise.

-  **Create apaquarto repos:** Create directories for 3 (temporary) apaquarto projects using each of the 3 setup methods. Connect each to a (temporary) github repository. Play around to find where there is flexibility and where things can break. 
-  **Simple .qmd notebook:** Create a new quarto notebook (.qmd), and follow all best practices for notebooks and code chunks as you work. Add a YAML header, at least 1 setup code chunk, at least 1 non-setup code chunk, and narrative text formatted with markdown.
    -   Associated mini-project: `05_data-communication/02_simple-qmd`


:::
::::
:::::::
::::::::::::::::::::::::::::::
