
<!-- 

Find and replace:

- 5 : week number (numeral only)
- 1 : class number (per week, numeral only)
- Monday, February 3, 2025 : date in format Monday, January 1, 2025
- A Grammar of Graphics : brief title/topic of the class meeting

TODO: see if there's a way to make these variables
The problem is that if they are includes with multiple on the index page, the variables would need to process before being included. 

-->

<!--
#### Announcements/Housekeeping/Etc

Text to appear before the accordion

-->

:::::::::::::::::::::::::::::: {#w5c1 .accordion}

:::: accordion-item
::: {.accordion-header .titlebox}
Week 5 | Class 1
:::
::::

:::: accordion-item
::: {.datebox}
Monday, February 3, 2025
:::
::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .prepbox type="button" data-bs-toggle="collapse" data-bs-target="#prep-w5c1" aria-expanded="false" aria-controls="prep-w5c1"}
**Before class:** ggplot2 resources
:::
::::

:::: {#prep-w5c1 .accordion-collapse .collapse data-bs-parent="#w5c1"}
::: accordion-body
**Readings & Resources:** 

- Chapters on data visualization and ggplot in r4ds: [1](https://r4ds.hadley.nz/data-visualize) and [9, 10, 11](https://r4ds.hadley.nz/visualize)
- [ggplot2 cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/data-visualization.pdf)
- [ggplot2-Book](https://ggplot2-book.org/) (note: 3e is currently “under construction” but it’s still a great resource!)


:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .classbox type="button" data-bs-toggle="collapse" data-bs-target="#class-w5c1" aria-expanded="false" aria-controls="class-w5c1"}
**Class meeting:** A Grammar of Graphics
:::
::::

:::: {#class-w5c1 .accordion-collapse .collapse data-bs-parent="#w5c1"}
::: accordion-body

**Materials:**

- [Slides](https://uchicago.box.com/s/q8wn46x23pe6zj3hexpu0uc8mwlbqbo9) *(v1 2/3/25 12:30pm)*
- [Cloning the assessment repo](resources/guides/origin-upstream-repos.qmd)
- [ggplot2 walkthrough part 1](https://github.com/nrdowling/d2mr-assessment/blob/main/03_data-viz/00_viz-walkthrough/data-viz-walkthrough-1.qmd)
    -   You can access this and run it as a stand-alone document without the rest of the repo

**Class plans:**

- Lecture: Introduction to Data Visualization with ggplot2 (A grammar of graphics)
- Activities:
    -   Fix the fork problem
    -   ggplot2 walkthrough part 1 (together with slides)

:::
::::
:::::::


::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .infobox type="button" data-bs-toggle="collapse" data-bs-target="#info-w5c1" aria-expanded="false" aria-controls="info-w5c1"}
**Info:** Fork/clone situation; Friday's workshop
:::
::::

:::: {#info-w5c1 .accordion-collapse .collapse data-bs-parent="#w5c1"}
::: accordion-body
**Reminders:**

- **Assessment repo changes:** We are moving to a new system where you will clone the assessment repo and then set the upstream repo to the main class repo. This is an alternative to forking that gives us (instructors) more control over the upstream repo and you more control over your own repo. [See the guide here](resources/guides/origin-upstream-repos.qmd).
    -   **This change is mandatory.** I know this is coming at a bad time and will be very frustrating for some people. I'm here to help! Please post issues in the Slack so we can resolve things quickly.
    -   *What do I do with my fork?* No matter what, create a local backup first. I suggest deleting your fork when you are confident the new clone system is set up and working correctly. That will help avoid confusion (on your end and mine) about which repo is the "real" one, it will prevent accidental pull requests to the main repo, and it will ensure you're the only one with full control over your work.
    -   *I'm working on a mini-project now in my fork, what do I do?* If you clone your forked repo, all your ongoing work will be in the new repo. Double check that the cloned files are up to date, then continue working in the *clone* and abandon the work in your fork.
    -   *What if I already submitted mini-projects with my fork?* Not a problem. You have two options: 1) Leave your fork up for now until your projects have been graded (and finalized by Dr. Dowling). When your grade is finalized, copy the graded assessment.md file into your new clone so that you have a record of your progress in your in-use repo. 2) Resubmit your mini-project to Canvas with a link to the directory in your new clone repo. In either case, once there are no outstanding submitted Canvas assignments with links to your fork, I recommend deleting your fork.
- **Friday's workshop:** Friday's class will be a data visualization workshop. Unlike the Week 4 workshop, this won't be a "free work" period. You should come prepared to discuss your needs and goals for visualizing data for your final research project. We'll work as a class to concetpualize what your plots should look like and prepare to make them in ggplot.
    -   If needed, we will devote about 15 minutes to resolving issues with the GitHub change, but we have to limit that time. Please use Slack and your troubleshooting resources to resolve as many issues as possible before Friday.


:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .todobox type="button" data-bs-toggle="collapse" data-bs-target="#post-5c1" aria-expanded="false" aria-controls="after-w5c1"}
**After class:** Fix your repo, start data viz projects
:::
::::

:::: {#post-5c1 .accordion-collapse .collapse data-bs-parent="#w5c1"}
::: accordion-body

**To-do:** 

1.  Download the ggplot2 cheatsheet
2.  Migrate from the github forked assessment repo to a new cloned repo, following the directions [in this guide](resources/guides/origin-upstream-repos.qmd) and getting support on Slack if needed
3.  Prepare for Friday's workshop by picking 2 tentative plans to visualize data for your final research project. Be ready to share in small groups and as a whole class!

**Recommended exercises:** 

-   **Data visualization structured exercises:**
    -   Walkthrough: Introduction to data visualizaton with ggplot2 (pt1)
        -   Demo only! This is the demo the lectures follow along with. Part 2 will be added next week.
        -   Associated mini-project: `03_data-viz/00_viz-walkthrough`
    -   Level 1: Visualize the mtcars Dataset
        -   Work with a simple dataset to recreate 3 basic plots (using only data, aes, and geoms) and 3 intermediate plots that add other commonly used elements.
        -   Associated mini-project: `03_data-viz/01_viz-level-1`
    -   Level 2: Visualize the starwars Dataset
        -   Work with a more complex dataset to recreate 1 advanced (and hideous) plot using many layers and theme elements.
        -   Associated mini-project: `03_data-viz/02_viz-level-2`

:::
::::
:::::::
::::::::::::::::::::::::::::::
