
<!-- 

Find and replace:

- 5 : week number (numeral only)
- 2 : class number (per week, numeral only)
- Friday, February 7, 2025 : date in format Monday, January 1, 2025
- Visualization Workshop : brief title/topic of the class meeting

TODO: see if there's a way to make these variables
The problem is that if they are includes with multiple on the index page, the variables would need to process before being included. 

-->

<!--
#### Announcements/Housekeeping/Etc

Text to appear before the accordion

-->

:::::::::::::::::::::::::::::: {#w5c2 .accordion}

:::: accordion-item
::: {.accordion-header .titlebox}
Week 5 | Class 2
:::
::::

:::: accordion-item
::: {.datebox}
Friday, February 7, 2025
:::
::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .prepbox type="button" data-bs-toggle="collapse" data-bs-target="#prep-w5c2" aria-expanded="false" aria-controls="prep-w5c2"}
**Before class:** Data viz theory to application
:::
::::

:::: {#prep-w5c2 .accordion-collapse .collapse data-bs-parent="#w5c2"}
::: accordion-body

**Readings & resources:**

- [from Data to Viz](https://www.data-to-viz.com/) (interactive guide for selecting appropriate visualization)
- [Be Awesome in ggplot2: A Practical Guide to be Highly Effective](https://www.sthda.com/english/wiki/be-awesome-in-ggplot2-a-practical-guide-to-be-highly-effective-r-software-and-data-visualization)
- [Designing effective data visualization](https://guides.library.jhu.edu/datavisualization/design) (Johns Hopkins Libraries)
- [Ten Simple Rules for Better Figures](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003833)

**Tasks:**

- Plan to workshop 1 or 2 plots from your final research project data in class, in both large group and small group settings. The “from Data to Viz” link above can be a good starting point.
- Take a look at the new mini-projects that have been posted this week (there are a lot!). In addition to projects about data visualization, there are instructions for most MPs in the “miscellaneous” category and a handful of others in other categories. If you see a project that is interesting to you but see that you don’t know everything you would need to complete 100% of the project, remember it’s totally ok to simplify the projects or focus just on the skills do you know instead of waiting until you’ve got everything mastered.

:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .classbox type="button" data-bs-toggle="collapse" data-bs-target="#class-w5c2" aria-expanded="false" aria-controls="class-w5c2"}
**Class meeting:** Data visualization Workshop
:::
::::

:::: {#class-w5c2 .accordion-collapse .collapse data-bs-parent="#w5c2"}
::: accordion-body

**Class plans:**

- Activities: (no lecture)
    -   (if needed) 15 minutes support for github clone setup
    -   Large group visualization workshop
    -   Small group visualization collaboration

:::
::::
:::::::


::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .infobox type="button" data-bs-toggle="collapse" data-bs-target="#info-w5c2" aria-expanded="false" aria-controls="info-w5c2"}
**Info:** Engagement grades
:::
::::

:::: {#info-w5c2 .accordion-collapse .collapse data-bs-parent="#w5c2"}
::: accordion-body

**Reminders:**

- **Mid-quarter engagement grades**: *Provisional* community engagement grades are posted Friday Week 5. This is to give you a sense of what you can expect your final engagement grade to be if you continue participating in class at the same level you have been so far. Remember:
    - Grades are assigned by Dr. Dowling, with input from TAs about how they have seen students engage that Dr. Dowling may not see
    - These grades will be fully replaced at the end of the quarter, and no matter what your grade is now there is the potential to gain all 10 points by the end of the quarter.
    - The easiest way to bump up your grade is by participating more on Slack. You can see more suggestions for how to raise this component of your grade [here](https://nrdowling.com/d2mr/syllabus/grading.html#community-engagement).
    - Feel like your grade doesn’t accurately reflect your engagement thus far? Two possibilities:
        - *You could be wrong.* Not that you’re not trying, but that you may be overestimating your engagement relative to the course expectations. Take a minute to reflect a bit on your participation thus far, read over the suggestions for ways to engage, and consider that this grade starts at 0, not 10 (you earn points; you don’t lose them).
        - *You could be right!* If you think you’re engaging in ways that Dr. Dowling and the TAs haven’t noticed, you can let us know! The “Community Engagement” assignment on Canvas (where you see the provisional grade) has an optional submission component. You can use this submission as a way to show/tell us how you’ve been an active part of the class community in ways we aren’t aware of. You can submit and resubmit to this assignment as many times as you like over the rest of the quarter, but you won’t receive a re-evaluated numeric grade until the end of the quarter.
    - Aside from giving us more information about your own engagement, **please use the assignment submission to let us know how you have seen your classmates positively engage with the community!** Someone start a study group? Help you debug your code for 2 hours on a Sunday night out of the goodness of their heart? Give you particularly useful insight during a class workshop? Use this as a place to give them a shout out so they can get the points they deserve.



:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .todobox type="button" data-bs-toggle="collapse" data-bs-target="#post-5c2" aria-expanded="false" aria-controls="after-w5c2"}
**After class:** More ggplot; make a timeline; additional MPs
:::
::::

:::: {#post-5c2 .accordion-collapse .collapse data-bs-parent="#w5c2"}
::: accordion-body

**To-do:** Make a submission plan & timeline

You’re (more than) half way through the quarter — how far along are you toward earning the 50 mini-project points and 40 research project points? Given that projects allow you to show cumulatively built skills, it’s reasonable to expect that it will be easier to earn more points in the second half of the quarter once you’ve got a lot of the basics under your belt.

Take a few minutes to make plan for how you’re going to earn the points you need for the grade you want. Are the mini-projects overwhelming? Maybe you want to turn in a lot of small projects instead of a couple big ones. Are they boring? Design your own! Confused by the grading? The sooner you turn in projects, the sooner you get a sense of how grading works, and the more time you leave yourself to earn all the points you want.

Same goes for the final research project. You’ve got 4 tries to earn the full 40 points, and you do not have to aim to meet all 40 at once. In fact, I strongly suggest you do *not* wait until you’re at a point where you can reasonably get everything at once. By that point we’ll be very late in the quarter, and you probably won’t have time to submit more than one try.

**Recommended exercises:**

- **Data visualization exercises:**
    - Data visualization Level 1 and Level 2 mini-projects (posted after last class)
        - Associated mini-project: `03_data-viz/01_viz-level-1`
        - Associated mini-project: `03_data-viz/02_viz-level-2`
    - Group/pairs swap plots
        - Work with a partner to create and recreate data visualizations using ggplot2. Each partner will create a complex visualization from a dataset, then challenge their partner to recreate it using only the dataset and a static image of the final plot.
        - Associated mini-project: `03_data-viz/04_group-swap-plots`
    - Create a plotting function
        - Define a function that creates customized plots using ggplot2. Your final product should be an .R script that defines your function, then demonstrates its use with various datasets and argument combinations. The function should serve a useful purpose in data visualization while incorporating tidyverse principles.
        - Associated mini-project: `06_r-programming/02_plotting-function`
- **Other recently published exercises:**
    - Data wrangling
        - (Off the syllabus) Wrangling non-rectangular and nested data - `02_data-wrangling/04_ots-nonrect-nested`
    - Data communication
        - Transpose an existing document to quarto - `05_data-communication/01_transpose-to-quarto`
        - Create a demo for a class topic - `05_data-communication/03_class-topic-demo`
    - R Programming
        - (Off the syllabus) Create and host a package - `06_r-programming/05_ots-create-package`
    - Unassessed/miscellaneous
        - Create and maintain a debugging journal - `08_unassessed-misc/02_debugging-journal`
        - Communicating concepts - `08_unassessed-misc/04_concepts`
        - Explore and apply LaTeX styling - `08_unassessed-misc/05_latex`
        - Contribute to StackOver or other crowdsource sites - `08_unassessed-misc/06_contribution`
        - Create a tutorial on a topic of your choice - `08_unassessed-misc/07_tutorial`

:::
::::
:::::::
::::::::::::::::::::::::::::::
