
<!-- 

Find and replace:

- 6 : week number (numeral only)
- 1 : class number (per week, numeral only)
- Monday, February 10, 2025 : date in format Monday, January 1, 2025
- "Pretty" plots : brief title/topic of the class meeting

TODO: see if there's a way to make these variables
The problem is that if they are includes with multiple on the index page, the variables would need to process before being included. 

-->

<!--
#### Announcements/Housekeeping/Etc

Text to appear before the accordion

-->

:::::::::::::::::::::::::::::: {#w6c1 .accordion}

:::: accordion-item
::: {.accordion-header .titlebox}
Week 6 | Class 1
:::
::::

:::: accordion-item
::: {.datebox}
Monday, February 10, 2025
:::
::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .prepbox type="button" data-bs-toggle="collapse" data-bs-target="#prep-w6c1" aria-expanded="false" aria-controls="prep-w6c1"}
**Before class:** Advanced ggplot2; apaquarto figures
:::
::::

:::: {#prep-w6c1 .accordion-collapse .collapse data-bs-parent="#w6c1"}
::: accordion-body

**Readings & Resources**:

- General ggplot2 data visualization:
    - Data Viz with ggplot2: [facets](https://viz-ggplot2.rsquaredacademy.com/ggplot2-facets)
    - ggplot2 documentation: [themes](https://ggplot2.tidyverse.org/reference/ggtheme.html)
    - ggplot2-Book:
        - [Layers](https://ggplot2-book.org/toolbox) (especially ch3, 4, 5)
        - [Scales](https://ggplot2-book.org/scales)
        - [The Grammar](https://ggplot2-book.org/mastery)
- [The R Graph Gallery](https://r-graph-gallery.com/)
- Figures in APA & Quarto
    - [Figures in APA7](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/apa_tables_and_figures.html)
    - [Quarto figures](https://quarto.org/docs/authoring/figures.html)
    - [apaquarto figures](https://wjschne.github.io/apaquarto/writing.html#figures)

**Tasks:**

Access the `d2mr-apaquarto` [repository on GitHub](https://github.com/nrdowling/d2mr-apaquarto.git). Optionally, clone the repo to play around with the files. You can set up a relationship to the upstream repo to pull in changes if you want, but it's not necessary if you don't want the git headache.

:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .classbox type="button" data-bs-toggle="collapse" data-bs-target="#class-w6c1" aria-expanded="false" aria-controls="class-w6c1"}
**Class meeting:** "Pretty" plots
:::
::::

:::: {#class-w6c1 .accordion-collapse .collapse data-bs-parent="#w6c1"}
::: accordion-body

**Materials:**

- [Slides](https://uchicago.box.com/s/q07qfy8emxsbmmmv9bleycle4xz6r3z9) *(v1 2/20/25 @11am)*
- Data viz walkthrough part 2 (`03_data-viz/00_viz-walkthrough-2`)
- [Example apaquarto manuscript](https://github.com/nrdowling/d2mr-apaquarto/blob/main/apaquarto-manuscript.qmd) ([d2mr-apaquarto](https://github.com/nrdowling/d2mr-apaquarto) repo)

**Class plans:**

- Lecture: Pretty plots
- Small groups: .qmd figures

:::
::::
:::::::


::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .infobox type="button" data-bs-toggle="collapse" data-bs-target="#info-w6c1" aria-expanded="false" aria-controls="info-w6c1"}
**Info:** Notes on grading
:::
::::

:::: {#info-w6c1 .accordion-collapse .collapse data-bs-parent="#w6c1"}
::: accordion-body

**Grading notes** 

- **Meeting objectives:** To make sure you get credit for the objectives you attempt to demonstrate, read through the assessment doc before submission to see if you’ve done the suggested tasks for each. For example:
    - **(5) Find, install, require, and load R packages:** Did you use more than one function?
    - **(6) Use arithmetic, comparison, and logical operators:** Did you use all 3 types?
    - **(8) Parse and write conditional statements and/or loops:** Do your conditionals use more than one function in more than one context?
    - **(9) Use `readr` functions to read in and write out data:** Will your script read in data for your grader (use relative paths!)?
    - **(22) Create and effectively use code chunks following best practices:** Do all your chunks have unique and informative labels?
    - **(26) Create and maintain a quarto document YAML header:** Does your header include options for an APA styled document?
    - You *can* still get credit for an objective without exactly matching the recommended tasks, but you’ll need to show effort and capability that is essentially the equivalent. If you believe you’ve done so, make a note of how you’ve shown comparable skills in your assessment document.
- **Objective categories:** When you’re attempting objectives, be conscious of the category each is under. Keep the broader context in mind. For example:
    - **Git and GitHub:** These objectives should show your abilities to create and maintain projects using git. Working in a git repository that you didn’t make or editing a readme file that you didn’t create doesn’t showcase your skills (it showcases mine). Effectively using version control doesn’t just mean you pushed to github, it means you’re using the git and github systems as an effective replacement for *not* using the git systems.
    - **Notebooks and code chunks:** These objectives should demonstrate your ability to effectively use markdown notebooks to execute skills demonstrated elsewhere. Maybe you made beautiful ggplots that met all plotting objectives, but to get (24) you need to integrate those figures into a notebook, including referencing it in the text. It’s not about the plotting skills; it’s about the markdown and notebook skills.
    - **R Markdown and Quarto:** These objectives should show your ability to create and maintain publication quality documents — the manuscript part of “Data to Manuscript.” Like with Git/GitHub, you’ll need to show your abilities to create and maintain (not mine), and you’ll need to show how the skills work in a publication-styled document. For example, to show “(27) Use quarto R Markdown to compose an academic manuscript,” it’s not enough to just use bold formatting and create lists; you need to show the markdown formatting in an academic manuscript.
- **Ask us!** If you’re feeling uncertain about what “counts” or you don’t understand your grades, ask Dr. Dowling and your TA for help understanding.

:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .todobox type="button" data-bs-toggle="collapse" data-bs-target="#post-6c1" aria-expanded="false" aria-controls="after-w6c1"}
**After class:** Secure data; level 2 data viz exercises
:::
::::

:::: {#post-6c1 .accordion-collapse .collapse data-bs-parent="#w6c1"}
::: accordion-body

**Tasks:**

- Using public data? Download everything you need locally. The politics of research right now is unpredictable and horrifying. Control what little you can by creating a local version of data or any other materials needed for your work.

**Recommended exercises:**

- Data visualization walkthrough (part 2)
    - Continuation of the ggplot demo. Part 2 covers more advanced skills, including the scales, facets, and theme layers.
    - Associated files: `03_data-viz/00_data-viz-walkthrough-2`
- Create a ggplot2 theme
    - Create a custom ggplot2 theme that reflects your personal visualization style while maintaining clarity and professionalism (or not). Your theme should be reusable across different types of plots and demonstrate understanding of ggplot2's theming system, including effective uses of the `theme()` layer and (optionally) non-data-dependent visual elements created as arguments of non-theme layers.
    - Associated mini-project: `03_data-viz/03_ggplot-theme`
- (OTS) Non-ggplot figures
    - Create a data visualization project that demonstrates your ability to create publication-quality plots using R packages other than ggplot2. You may use alternatives to ggplot2 or extensions.
    - Associated mini-project: `03_data-viz/06_ots-non-ggplot`

:::
::::
:::::::
::::::::::::::::::::::::::::::
