
<!-- 

Find and replace:

- 6 : week number (numeral only)
- 2 : class number (per week, numeral only)
- Friday, February 14, 2025 : date in format Monday, January 1, 2025
- Tables : brief title/topic of the class meeting

TODO: see if there's a way to make these variables
The problem is that if they are includes with multiple on the index page, the variables would need to process before being included. 

-->

<!--
#### Announcements/Housekeeping/Etc

Text to appear before the accordion

-->

:::::::::::::::::::::::::::::: {#w6c2 .accordion}

:::: accordion-item
::: {.accordion-header .titlebox}
Week 6 | Class 2
:::
::::

:::: accordion-item
::: {.datebox}
Friday, February 14, 2025
:::
::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .prepbox type="button" data-bs-toggle="collapse" data-bs-target="#prep-w6c2" aria-expanded="false" aria-controls="prep-w6c2"}
**Before class:** Table resources & packages
:::
::::

:::: {#prep-w6c2 .accordion-collapse .collapse data-bs-parent="#w6c2"}
::: accordion-body
**Readings & documentation:**

- R Graph Gallery’s [guide to table packages](https://r-graph-gallery.com/table.html)
- [Pandoc tables](https://pandoc.org/chunkedhtml-demo/8.9-tables.html)
- r4ds: [28.8 Tables](https://r4ds.hadley.nz/quarto.html#tables)
- apaquarto: [Tables](https://wjschne.github.io/apaquarto/writing.html#tables)
- Quarto: [Tables](https://quarto.org/docs/authoring/tables.html)
- RMarkdown Cookbook: [Ch10 Tables](https://bookdown.org/yihui/rmarkdown-cookbook/tables.html)

**Packages for table-making:**

- [knitr](https://yihui.org/knitr/) (kables) and [kableExtra](https://haozhu233.github.io/kableExtra/) (better kables)
- [stargazer](https://www.rdocumentation.org/packages/stargazer/versions/5.2.3/topics/stargazer) package for statistical reporting & [tutorial](https://libguides.princeton.edu/R-stargazer)
- [flextable](https://davidgohel.github.io/flextable/index.html) package and [extensive guide](https://ardata-fr.github.io/flextable-book/index.html)
- [gt](https://gt.rstudio.com/) (Grammar of Tables), [gtsummary](https://www.danieldsjoberg.com/gtsummary/), & [gtextras](https://jthomasmock.github.io/gtExtras/)

:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .classbox type="button" data-bs-toggle="collapse" data-bs-target="#class-w6c2" aria-expanded="false" aria-controls="class-w6c2"}
**Class meeting:** Tables
:::
::::

:::: {#class-w6c2 .accordion-collapse .collapse data-bs-parent="#w6c2"}
::: accordion-body

**Materials:**

- [Slides]()

**Class plans:**

- Lecture & demo: Making tables in Quarto

:::
::::
:::::::


::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .infobox type="button" data-bs-toggle="collapse" data-bs-target="#info-w6c2" aria-expanded="false" aria-controls="info-w6c2"}
**Info:** Research project progress
:::
::::

:::: {#info-w6c2 .accordion-collapse .collapse data-bs-parent="#w6c2"}
::: accordion-body
**Check-in:** How's your final research project going? How many drafts have you submitted? How many points off the full 40 are you? How many points do you think you'd get if you turned in what you have right now? How confident are you that you know what you need to get the grade you want? If you're feeling at all unsure about your final project, **turn something in now.** If it's a mess and you would get a bad grade, wouldn't you rather find that out now while you have several weeks to turn that bad grade into a perfect score?

:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .todobox type="button" data-bs-toggle="collapse" data-bs-target="#post-6c2" aria-expanded="false" aria-controls="after-w6c2"}
**After class:** Start thinking stats
:::
::::

:::: {#post-6c2 .accordion-collapse .collapse data-bs-parent="#w6c2"}
::: accordion-body

**Tasks:**

- **Before Monday, decide on at least 1 descriptive analysis you would like to conduct with your data.** It’s time to make a preliminary analysis plan for your research project data. On Monday we’ll talk about executing simple descriptive statistics in R, and on Friday we’ll cover simple hypothesis testing. Neither of these sessions is intended to be a stats class. We’ll learn how to execute analyses in R and we’ll go over the absolute basics of what different kinds of tests are used for, but it is up to you to know what you need to do in the best interests of your project.
:::
::::
:::::::
::::::::::::::::::::::::::::::
