
<!-- 

Find and replace:

- 8 : week number (numeral only)
- 1 : class number (per week, numeral only)
- Monday, February 24, 2025 : date in format Monday, January 1, 2025
- Dynamic text : brief title/topic of the class meeting

TODO: see if there's a way to make these variables
The problem is that if they are includes with multiple on the index page, the variables would need to process before being included. 

-->

<!--
#### Announcements/Housekeeping/Etc

Text to appear before the accordion

-->

:::::::::::::::::::::::::::::: {#w8c1 .accordion}

:::: accordion-item
::: {.accordion-header .titlebox}
Week 8 | Class 1
:::
::::

:::: accordion-item
::: {.datebox}
Monday, February 24, 2025
:::
::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .prepbox type="button" data-bs-toggle="collapse" data-bs-target="#prep-w8c1" aria-expanded="false" aria-controls="prep-w8c1"}
**Before class:** Cross-references and inline code
:::
::::

:::: {#prep-w8c1 .accordion-collapse .collapse data-bs-parent="#w8c1"}
::: accordion-body
**Readings & Resources:**

- Quarto Documentation
    - [Inline code](https://quarto.org/docs/computations/inline-code.html)
    - [Cross-references](https://quarto.org/docs/authoring/cross-references.html)
- Quarto for Scientists (Tierney, 2024)
    - [Citing figures, tables, and sections](https://qmd4sci.njtierney.com/cite-fig-tab-sec.html)
    - [Inline code](https://qmd4sci.njtierney.com/using-qmd.html#inline-code)
- Datanovia
    - [Quarto Cross References](https://www.datanovia.com/guide/tools/quarto/cross-references.html)
    - [Quarto Computations](https://www.datanovia.com/guide/tools/quarto/r.html) (code blocks and inline code)

:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .classbox type="button" data-bs-toggle="collapse" data-bs-target="#class-w8c1" aria-expanded="false" aria-controls="class-w8c1"}
**Class meeting:** Dynamic text, part 1 
:::
::::

:::: {#class-w8c1 .accordion-collapse .collapse data-bs-parent="#w8c1"}
::: accordion-body

**Materials:**

- [Slides](https://uchicago.box.com/s/ih8ryg2egjcjqk827asvqotakn7uabcx) *(v2 2/24/25 @1:00pm)*
    - Note: These slides will be used for both Monday and Friday of Week 8
- [d2mr-apaquarto repo](https://github.com/nrdowling/d2mr-apaquarto)

**Class plans:**

- Lecture: Dynamic text, part 1 (cross-references, inline R code)
- Referencing and code demo with the d2mr-apaquarto repo

:::
::::
:::::::


::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .infobox type="button" data-bs-toggle="collapse" data-bs-target="#info-w8c1" aria-expanded="false" aria-controls="info-w8c1"}
**Info:** End of quarter deadlines; grading
:::
::::

:::: {#info-w8c1 .accordion-collapse .collapse data-bs-parent="#w8c1"}
::: accordion-body
**Deadlines:**

- Wednesday, February 26th (this week!!!): Last day to submit *and receive feedback on* a research project draft
- Wednesday, March 5th: Last day to submit mini-projects
- Wednesday, March 12th: Last day to submit final research projects

**Grading:**

-   **Timelines:** Grading can take a lot of time. Yuchen, Mian, and I are all grading as quickly as we can, and our goal is to get you feedback as soon as possible so you know what you need to do for the remainder of the quarter. For the most part, the TAs are handling mini-projects, and I am handling the research projects. We grade in the order that we receive submissions, so the earlier you submit, the earlier you'll get a grade. At this point in the quarter, everyone is submitting many projects and drafts at once, so you should expect a longer turnaround than submissions earlier in the quarter. 
-   **Feedback:** On your assessment form, there should be a commented explanation any time you do not receive credit for an attempted objective. In some cases you will get general comments on the submission as a whole, but in the interests of time, we are focusing on the objectives. If you don't see general feedback at the end of the assessment document, it's not because we didn't grade your work holistically and thoroughly. It's simply that we must be pragmatic with our time to get everyone feedback quickly.
-   **Research project assessment document:** The final research project has its own assessment document: `research-assessment.md`. You can find this file in the top level of your assessment repository. Copy and paste the document into your project's repo and complete in full. Please use the most up-to-date version of this document. 
    -   Changes to this document from the version posted at the beginning of the quarter:
        -   More detailed overall expectations for the project (structure, content, etc.)
        -   AI statement & optional AI use reflection
        -   Clarifications of expectations for some objectives
        -   Relaxed (easier to meet) expectations for some objectives
        -   Optional project reflection section
        -   Grading summary section
    -   If you submitted a draft on or before Sunday, February 23rd using an older version of the assessment, I have updated it for you.
    -   If you submit a draft on or after Monday, February 24th, you must use the most up-to-date version of the assessment document. Submissions using the older version will be asked to resubmit with the correct document. Since I won't notice the older assessment until I get to your draft in my grading queue, this may delay returning your graded work to you.
    -   When you submit a second (or later) draft of your research project, you should simply update the document that already has your previous feedback. Do not create a new assessment document and do not remove grader comments from the previous draft.
    

:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .todobox type="button" data-bs-toggle="collapse" data-bs-target="#post-8c1" aria-expanded="false" aria-controls="after-w8c1"}
**After class:** Preview and set up bibtex
:::
::::

:::: {#post-8c1 .accordion-collapse .collapse data-bs-parent="#w8c1"}
::: accordion-body
**To-do:**

- Preview the remainder of the slides for dynamic text (bibtex citations)
- Follow [the guide](https://nrdowling.com/d2mr/resources/guides/bibtex-citr-zotero.html) to setup a Zotero-citr workflow
    -   Time-permitting, we'll do this together in class on Friday. It's not terribly complicated though, so you can get a jump start on it to make early progress on the BibTeX requirements for your project.

**Recommended exercises:**

- No new mini-projects
- Mini-projects that are good opportunities to practice dynamic text references:
    - `05_data-communication/01_transpose-to-quarto`
    - `05_data-communication/02_simple-qmd`
    - `05_data-communication/03_class-topic-demo`
    - `08_unassessed-misc/07_tutorial`

:::
::::
:::::::
::::::::::::::::::::::::::::::
