
<!-- 

Find and replace:

- 8 : week number (numeral only)
- 2 : class number (per week, numeral only)
- Friday, February 28, 2025 : date in format Monday, January 1, 2025
- BibTeX & citr : brief title/topic of the class meeting

TODO: see if there's a way to make these variables
The problem is that if they are includes with multiple on the index page, the variables would need to process before being included. 

-->

<!--
#### Announcements/Housekeeping/Etc

Text to appear before the accordion

-->

:::::::::::::::::::::::::::::: {#w8c2 .accordion}

:::: accordion-item
::: {.accordion-header .titlebox}
Week 8 | Class 2
:::
::::

:::: accordion-item
::: {.datebox}
Friday, February 28, 2025
:::
::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .prepbox type="button" data-bs-toggle="collapse" data-bs-target="#prep-w8c2" aria-expanded="false" aria-controls="prep-w8c2"}
**Before class:** Citation resources; Zotero/citr setup
:::
::::

:::: {#prep-w8c2 .accordion-collapse .collapse data-bs-parent="#w8c2"}
::: accordion-body
**Readings & Resources:**

- D2MR Guide: [BibTeX References with Zotero & citr](https://nrdowling.com/d2mr/resources/guides/bibtex-citr-zotero.html)
- [BibTeX Format Overview](https://www.bibtex.org/Format/)
- [Customizing citation keys](https://retorque.re/zotero-better-bibtex/citing/)
- Quarto documentation: [Citations](https://quarto.org/docs/authoring/citations.html)
- apaquarto documentation: [Citations](https://wjschne.github.io/apaquarto/writing.html#citations)
- Pandoc documentation: [Citations](https://pandoc.org/MANUAL.html#citations)
- papaja documentation: Citations, specifically…
    - [Inserting citations with citr](https://frederikaust.com/papaja_man/writing.html#conveniently-inserting-citations-with-citr)
    - [Citing R and its Packages](https://frederikaust.com/papaja_man/writing.html#citing-r-and-its-packages) (w/ `r_refs()` and `cite_r()` )

**Software & Tools:**

Although you are not required to use the Zotero - Better BibTeX - citr workflow, I strongly recommend at least trying it. Follow the [class guide to set it up](https://nrdowling.com/d2mr/resources/guides/bibtex-citr-zotero.html), or use just the elements you find most useful.

- [Zotero](https://www.zotero.org/) (free citation management)
- [Better BibTeX](https://retorque.re/zotero-better-bibtex/) (Zotero extension)
- [citr](https://github.com/crsh/citr) (RStudio package/addin)
    - Note: This package is not on CRAN and cannot be installed with `install.packages()`. Use `devtools::install_github("crsh/citr")` instead.
- [CSL Project](https://citationstyles.org/) (many, *many* pre-built .csl files for common and uncommon citation styles)
    - The [github](https://github.com/citation-style-language/styles) with the actual files
    - Note: apaquarto will use its own embedded APA7 .csl by default. You can override this or edit the file within the extension, but I don’t recommend it unless you know exactly why you need to and how to do so.

:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .classbox type="button" data-bs-toggle="collapse" data-bs-target="#class-w8c2" aria-expanded="false" aria-controls="class-w8c2"}
**Class meeting:** Dynamic text, part 2
:::
::::

:::: {#class-w8c2 .accordion-collapse .collapse data-bs-parent="#w8c2"}
::: accordion-body

**Materials:**

- [Slides](https://uchicago.box.com/s/ih8ryg2egjcjqk827asvqotakn7uabcx) *(v2 2/24/25 @1:00pm)*
    - Note: These slides will be used for both Monday and Friday of Week 8
- [d2mr-apaquarto repo](https://github.com/nrdowling/d2mr-apaquarto)

**Class plans:**

- Lecture: Dynamic text, part 2 (citations)
- Zotero/Better BibTeX workflow walkthrough
- Citations and code demo with the d2mr-apaquarto repo

:::
::::
:::::::


::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .infobox type="button" data-bs-toggle="collapse" data-bs-target="#info-w8c2" aria-expanded="false" aria-controls="info-w8c2"}
**Info:** Deadline reminders
:::
::::

:::: {#info-w8c2 .accordion-collapse .collapse data-bs-parent="#w8c2"}
::: accordion-body
**Deadlines:**

- ~~Wednesday, February 26th (this week!!!): Last day to submit *and receive feedback on* a research project draft~~
- Wednesday, March 5th: Last day to submit mini-projects
- Wednesday, March 12th: Last day to submit final research projects
:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .todobox type="button" data-bs-toggle="collapse" data-bs-target="#post-8c2" aria-expanded="false" aria-controls="after-w8c2"}
**After class:** Crunch time!
:::
::::

:::: {#post-8c2 .accordion-collapse .collapse data-bs-parent="#w8c2"}
::: accordion-body

**Next week:**

**Today is the last day of new material.** You now have everything you need to tackle all the (non-OtS) mini-projects and complete your final research project meeting all 30 objectives.

Classes next week will have minimal lecture, instead being primarily time to review the essentials, ask any lingering questions about class material, preview some directions you can take things beyond this course, and work on your mini-projects (Monday only, since they’re due Wednesday!) and final projects.

This weekend is the start of “crunch time” to work toward any remaining objectives points you need for the MPs and final project. Plan accordingly!

:::
::::
:::::::
::::::::::::::::::::::::::::::
