
<!-- 

Find and replace:

- 9 : week number (numeral only)
- 1 : class number (per week, numeral only)
- Monday, March 3, 2025 : date in format Monday, January 1, 2025
- Making the most of Quarto : brief title/topic of the class meeting

TODO: see if there's a way to make these variables
The problem is that if they are includes with multiple on the index page, the variables would need to process before being included. 

-->

<!--
#### Announcements/Housekeeping/Etc

Text to appear before the accordion

-->

:::::::::::::::::::::::::::::: {#w9c1 .accordion}

:::: accordion-item
::: {.accordion-header .titlebox}
Week 9 | Class 1
:::
::::

:::: accordion-item
::: {.datebox}
Monday, March 3, 2025
:::
::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .prepbox type="button" data-bs-toggle="collapse" data-bs-target="#prep-w9c1" aria-expanded="false" aria-controls="prep-w9c1"}
**Before class:** Work on your projects!
:::
::::

:::: {#prep-w9c1 .accordion-collapse .collapse data-bs-parent="#w9c1"}
::: accordion-body

We’re done with new material. Work on finishing mini-projects and making progress on your final research project. We'll be workshopping for some of class on Monday and all of class on Friday, so plan ahead for what you want to focus on while you've got people around to help.

:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .classbox type="button" data-bs-toggle="collapse" data-bs-target="#class-w9c1" aria-expanded="false" aria-controls="class-w9c1"}
**Class meeting:** The D2MR Workflow
:::
::::

:::: {#class-w9c1 .accordion-collapse .collapse data-bs-parent="#w9c1"}
::: accordion-body

**Materials:**

- [Slides](https://uchicago.box.com/s/k2yi9h6d58xqb3i1cq7z6ybfv7axa2rv) *(v1 3/2/25 2:00pm)*

**Class plans:**

- Lecture: Putting it all together - the D2MR workflow
- Workshop (any remaining time): Collaborative work time for mini-projects and final projects

:::
::::
:::::::


::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .infobox type="button" data-bs-toggle="collapse" data-bs-target="#info-w9c1" aria-expanded="false" aria-controls="info-w9c1"}
**Info:** Deadlines, grades, engagement, office hours
:::
::::

:::: {#info-w9c1 .accordion-collapse .collapse data-bs-parent="#w9c1"}
::: accordion-body
**Deadlines:**

- Mini-projects are due **this Wednesday, March 5th** at 11:59pm
- Final drafts of research projects are due **next Wednesday, March 12th** at 11:59pm
    - No extensions
    - Syllabus is designed to allow students who need extended deadlines to pace their work throughout the quarter without having to make special requests
- Friday is the latest day to negotiate a pass/fail plan (but you should do this sooner rather than later!). If you are considering this option, reach out to Dr. Dowling as soon as possible.

**Grades:**

- Email me this week (ASAP!) to negotiate a pass/fail option
- [Grading scale (point to letter grade conversion)](https://nrdowling.com/d2mr/syllabus/grading.html)

**Community engagement:**

- Final engagement grades will replace the mid-quarter grades
- The Canvas assignment where you see the mid-quarter grade is actually a real assignment
    - You may (optionally) submit something to that assignment describing how you've been engaged in the class in ways I may not have seen
    - You may also use this to give credit to classmates who have been supportive
- Reminder: Engagement grades are not attendance grades or easy points. You earn up to 10 by doing more than the minimum.

**Office hours:**

- Dr. Dowling will hold extra office hours over Zoom during Week 9 and finals week. [Sign up here.](https://calendar.app.google/2LqctL2FQYLYU3Bt7)
    - Please do not sign up for more than 1 appointment!
        - If you would like to attend multiple, you can attend in pairs or groups (ie each individual student signs up for 1 appointment but everyone attends all of them together).
    - Meetings on Wednesday March 5th and Friday March 7th may take place either over Zoom or in person in my office. We’ll assume Zoom by default, but send me an email if you book one of those times and prefer to meet in person.
    - Unfortunately I do not have availability outside these extra time slots, but you are free to reach out to me or the TAs over email. And as always, post to Slack!
- Mian and Yuchen may hold additional office hours. We will keep you updated with Slack announcements.

:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .todobox type="button" data-bs-toggle="collapse" data-bs-target="#post-9c1" aria-expanded="false" aria-controls="after-w9c1"}
**After class:** Keep working on your projects!
:::
::::

:::: {#post-9c1 .accordion-collapse .collapse data-bs-parent="#w9c1"}
::: accordion-body
**Mini-project tips:** 

- Panicking? There’s a good chance you’re overthinking things.
    - Figure out what the bare minimum is that you would need to do to get the points you need for a project, and just do that.
    - Still have time for a little more? Great, put in a little more to count toward you engagement score.
    - Didn’t get everything done? Kind of a bummer, but whatever. Turn in what you have!
- Realizing you were overambitious?
    - Cut your losses and swap to an easier and/or more structured project. No judgment.
        - Actually some judgment, but in a good way. I will judge you positively for making a reasoned decision about priorities and organization.
- Review the graded assessment files for past MPs.
    - In some cases the TAs may have indicated you can revise and resubmit, in which case you should do that!
        - If they didn’t note it on your assessment, you can ask your TA if they will accept a resubmission, but it is entirely at their discretion. Remember the general policy is no MP resubmissions allowed — this is a kindness from the TAs!
    - Note where and why you missed attempted objectives. In many cases it is for very tiny things that are very easily fixable in the next project you complete.

**Final project tips:**

- Read the research-assessment.md document closely *before* you go to complete it for submission!!
    - Includes a thorough description of the overall expectations. Failing to meeting these will be reflected in your engagement score.
    - Includes detailed explanations for meeting each objective. Read these closely! There are many that are very easy to meet *and* very easy to miss
- I may give credit for work that does not meet all the outlined expectations for an objective *if* I believe it has demonstrated mastery of the objective in another way
- You are required to complete the AI statement. Failure to do so will result in a 5 point penalty.
- Use the most recent version of the assessment document! If you don't see a detailed list of overall expectations, a section for your AI statement, a reflection section, or a grading section, you've got the wrong version!
    - Aside from just missing these sections, you're missing important clarifications and simplifications for objective expectations.

:::
::::
:::::::
::::::::::::::::::::::::::::::
