
<!-- 

Find and replace:

- 9 : week number (numeral only)
- 2 : class number (per week, numeral only)
- Friday, March 7, 2025 : date in format Monday, January 1, 2025
- Your Data to Manuscript Workflow : brief title/topic of the class meeting

TODO: see if there's a way to make these variables
The problem is that if they are includes with multiple on the index page, the variables would need to process before being included. 

-->

<!--
#### Announcements/Housekeeping/Etc

Text to appear before the accordion

-->

:::::::::::::::::::::::::::::: {#w9c2 .accordion}

:::: accordion-item
::: {.accordion-header .titlebox}
Week 9 | Class 2
:::
::::

:::: accordion-item
::: {.datebox}
Friday, March 7, 2025
:::
::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .prepbox type="button" data-bs-toggle="collapse" data-bs-target="#prep-w9c2" aria-expanded="false" aria-controls="prep-w9c2"}
**Before class:** Submit mini-projects, work on final projects
:::
::::

:::: {#prep-w9c2 .accordion-collapse .collapse data-bs-parent="#w9c2"}
::: accordion-body

Mini-projects are (were) due Wednesday March 5th. Reading this before then? Great! Don’t forget to turn them in!

Work on making progress on your final research project. We'll be workshopping for all of class on Friday, so plan ahead for what you want to focus on while you've got people around to help.

:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .classbox type="button" data-bs-toggle="collapse" data-bs-target="#class-w9c2" aria-expanded="false" aria-controls="class-w9c2"}
**Class meeting:** Final project workshop
:::
::::

:::: {#class-w9c2 .accordion-collapse .collapse data-bs-parent="#w9c2"}
::: accordion-body

No lecture, no activities, just 80 minutes of time to work on your final research projects together with the professor, TA, and your classmates.

:::
::::
:::::::


::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .infobox type="button" data-bs-toggle="collapse" data-bs-target="#info-w9c2" aria-expanded="false" aria-controls="info-w9c2"}
**Info:** Deadlines & office hours
:::
::::

:::: {#info-w9c2 .accordion-collapse .collapse data-bs-parent="#w9c2"}
::: accordion-body

**Deadlines:**

- ~~Mini-projects are due **this Wednesday, March 5th** at 11:59pm~~
- Final drafts of research projects are due **next Wednesday, March 12th** at 11:59pm
    - No extensions
    - Syllabus is designed to allow students who need extended deadlines to pace their work throughout the quarter without having to make special requests
- Today (Friday Week 9) is the latest day to negotiate a pass/fail plan. If you are considering this option, reach out to Dr. Dowling as soon as possible.

**Office hours:**

- Dr. Dowling will hold extra office hours over Zoom during Week 9 and finals week. [Sign up here.](https://calendar.app.google/2LqctL2FQYLYU3Bt7)
    - Please do not sign up for more than 1 appointment!
        - If you would like to attend multiple, you can attend in pairs or groups (ie each individual student signs up for 1 appointment but everyone attends all of them together).
    - Meetings on Wednesday March 5th and Friday March 7th may take place either over Zoom or in person in my office. We’ll assume Zoom by default, but send me an email if you book one of those times and prefer to meet in person.
    - Unfortunately I do not have availability outside these extra time slots, but you are free to reach out to me or the TAs over email. And as always, post to Slack!
- Mian and Yuchen may hold additional office hours. We will keep you updated with Slack announcements.

:::
::::
:::::::

::::::: accordion-item
:::: accordion-header
::: {.accordion-button .collapsed .todobox type="button" data-bs-toggle="collapse" data-bs-target="#post-9c2" aria-expanded="false" aria-controls="after-w9c2"}
**After class:** Live your best life with data and manuscripts
:::
::::

:::: {#post-9c2 .accordion-collapse .collapse data-bs-parent="#w9c2"}
::: accordion-body

We’re done! 

- Submit your final draft by next Wednesday. Whatever you’ve submitted by 11:59pm on Wednesday will become your final grade for the project.
- Be on the lookout for a survey from me about the class and improvements for future quarters.
- Submit a community engagement reflection if you like.
- Please keep in touch with me and with each other! The Slack will stay open at least through Spring quarter.
- Going to be around next year? Let me know if you’re interested in TAing for D2MR!

:::
::::
:::::::
::::::::::::::::::::::::::::::
