---
title: "External Resources"
format: html
---

*Find a great resource that others might appreciate? Email Dr. Dowling to add to the list!*

## General

- [STAT545](https://stat545.com/)
    - The course website for a similar (and much more comprehensive!) course originated at UBC by Jenny Bryan
- [Experimentology](https://experimentology.io/)
    -   Introduction to the workflow of the experimental researcher working in behavioral sciences
    -   This book is *not* about R or programming, but covers many of the same workflow principles as D2M-R with much more depth on application of those principles to experimental research design and practice with several appendices that are more programming-focused

## Documentation & References

### Git & github

- [Git](https://git-scm.com/doc)
- [How to Use Git/GitHub with R](https://rfortherestofus.com/2021/02/how-to-use-git-github-with-r/) - Instructions for setting up your GitHub integration within RStudio, no GitHub Desktop required!
- [Git user manual](https://git-scm.com/docs/user-manual) - Look here if you want to use Git in the terminal or command line
- [Git cheat sheet](https://training.github.com/downloads/github-git-cheat-sheet/)
- [An introduction to Git and how to use it with RStudio](https://r-bio.github.io/intro-git-rstudio/)
- [Happy Git and GitHub for the useR](https://happygitwithr.com/) - A companion to STAT545 (see above)
- [Oh shit, Git!?!](https://ohshitgit.com/) - Plain English explanations to prevent git-induced panic attackes and/or migraines

### R

- [R for Data Science, second edition](https://r4ds.hadley.nz/) by Hadley Wickham
- [Hands-On Programming with R](https://rstudio-education.github.io/hopr/packages2.html) by Garrett Grolemund
- [User-contributed cheatsheets](https://posit.co/resources/cheatsheets/?type=contributed-cheatsheets/)
- [W3Schools R tutorial](https://www.w3schools.com/r/default.asp)
- [Learn-R](https://learn-r.org/)
- [Using R for psychological research - Personality Project](https://personality-project.org/r/)
- [R for Graduate Students](https://bookdown.org/yih_huynh/Guide-to-R-Book/)


### Quarto & Markdown

-   [Quarto](https://quarto.org/)
-   [apaquarto extension](https://github.com/wjschne/apaquarto)
-   [Quarto cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/quarto.pdf)
-   [Quarto for R Markdown Users](https://quarto.org/docs/faq/rmarkdown.html)
-   [R Markdown for Scientists](https://rmd4sci.njtierney.com/) by Nicholas Tierney
-   [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) by Yihui Xie, J. J. Allaire, and Garrett Grolemund
-   [R Markdown cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/rmarkdown.pdf)


### Tidyverse and R Packages

- [Tidyverse overview](https://tidyverse.tidyverse.org/)
- [Tidyverse cheatsheets](https://www.rstudio.com/resources/cheatsheets/)

### ggplot2 and Visualization

- [ggplot2 overview](https://ggplot2.tidyverse.org/)
- [ggplot2 cheatsheet](https://www.rstudio.com/resources/cheatsheets/)
- [ggplot2 Book](https://ggplot2-book.org/)
- [R Graph Gallery](https://r-graph-gallery.com/ggplot2-package.html)

## Transitioning to R

- [Stata to R :: cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/master/stata2r.pdf)
- [R for Stata Users](https://content.e-bookshelf.de/media/reading/L-6263-42442f4dac.pdf) (Muenchen & Hilbe)
- [R for SAS & SPSS Users](https://r4stats.com/books/free-version/) (Muenchen)
- [From SPSS to R](https://www.melissagwolf.com/spss-to-r/) (Wolf)
- [Switching from Matlab to R](https://www.clarkrichards.org/2014/01/19/switching-from-matlab-to-r-part-1/) (Richards)
- [R for MATLAB users](https://mathesaurus.sourceforge.net/octave-r.html) (cheatsheet-ish)


