---
title: "Communication Policy"
format: html
---

# Overview 

-   **Slack**: We will use Slack for most course communication. The Slack is moderated and only open to members of the class. You must use your UChicago email address to join.
    - Please use the appropriate Slack channel for your question or comment. Do not DM the professor or TAs; use email instead.
-  **Email**: Use email for private communication with Dr. Dowling or your TA. You should expect a response within about 2 days. If you have not received a response within 3 days please send a follow-up email.
-  **Office hours**: Dr. Dowling and TAs will hold office hours each week. You can find the schedule on the [course home page](../index.html). You can also make an appointment to meet outside of office hours if needed.

# Slack
    
We will use Slack for communication outside of class, aside from one-on-one discussion (which should happen in emails or in person). 
In addition to seeing important announcements from the instructors, you can use Slack to ask questions, share resources, and get help from your classmates. 
You can also use it to share your work and get feedback from your peers, or to find classmates to collaborate on group assignments. 

You can access the Slack workspace [here](). 

The primary purpose of using Slack is for students to support their peers. 
We encourage you to not only ask questions, but to reply to others' questions when you know the answer. 
This is a great way to solidify your own understanding of the material and to help your classmates.

## Channels

The Slack has separate channels for different topics as well as channels for each section. 
You can also create your own channels for group work or other purposes. 
Please use the appropriate channel for your question or comment! 
This keeps the workspace organized and helps others with similar questions (or answers!) find what they need.

The instructors will moderate the Slack workspace and respond to questions as needed, but typically will not be the first to respond.
This is intentional! 
We want to encourage you to help each other and to develop your own problem-solving skills. 
If you see a question that you know the answer to, share it! 
If you see a question that you *don't* know the answer to, but you know something that might be related or helpful, share that too! 
If you see a question and you have the same question, use a reaction to indicate that you're also interested in the answer, and respond with additional details about your similar question/problem if you have them.

## Direct messages

If you have a question, it is likely that others do too! 
This is the point of Slack, so please ask questions in the appropriate channel rather than using DMs. 
You may DM other students, but please be respectful and professional in your communication. 

**Please do not DM the professor or TAs on Slack.** 
If you have a question about the course material, post it in the appropriate channel so that everyone can benefit from the answer. 
If you want to make sure one of us sees it, you can tag us in it. 
If you have a question that pertains only to you, please discuss it with the professor or TAs over email or in office hours.

# Email

Email is the best way to reach Dr. Dowling or TAs for private communication.

You are welcome to email us whenever you like, but we will typically only respond during normal working hours (9am-5pm, Monday-Friday). You can usually expect us to respond within a day or two. 
If you have not received a response within 3 days (excluding weekends/holidays) feel free to send a follow-up email.

If you email us with questions we think are relevant to the whole class, we may ask you to post them in Slack instead.

Anxious about emailing professors? You can find suggestions and example emails at the end of this guide to the [~~Un~~written Rules of Higher-Ed Classrooms](https://nrdowling.notion.site/written-Rules-of-Higher-Ed-Classrooms-2cc7b904f28d805aa8bce014b958bc27?source=copy_link) (you may find the rest of the guide useful, too!).
