---
title: "Slides"
format: html
---

<!-- Note: Only link to .html files for slides, not .qmd. Slides are rendered in a different profile and calling theme here will cause conflicts when the site profile renders. -->

## D2M-R Quarter I Slides

-   Week 1: [Introduction to D2M-R](../slides/Q1-W1_introduction.html) and [Problem Solving Strategies](../slides/Q1-W1_problem-solving.html)
-   Week 2: 
    -   [Git & GitHub](../slides/Q1-W2_git-github.html)
    -   [RStudio & Quarto](../slides/Q1-W2_rstudio-quarto.html)
-   Week 3: [R Programming Language](../slides/Q1-W3_r-programming.html)
-   Week 4: [Welcome to the Tidyverse](../slides/Q1-W4_tidyverse-1.html)
-   Week 5: *no slides*
-   Week 6: 
    -   [Tidyverse Data Wrangling with Strings](../slides/Q1-W6_tidyverse-strings.html)
    -   [Tidyverse Data Wrangling with Factors](../slides/Q1-W6_tidyverse-factors.html)
-   Week 7 & 8: Data Reporting Essentials
    -   [Intro to Data Visualization](../slides/Q1-W7_reporting-1.html)
-   Week 9: [Dynamic References](https://uchicago.box.com/s/ih8ryg2egjcjqk827asvqotakn7uabcx)
    -   *Note:* This is an archived version of powerpoint slides used in a previous quarter of D2M-R. The course was organized differently (most notably, being centered on using the apaquarto extension and covering all content in a single quarter). Some links and content may be out of date, and not all content will be applicable to D2M-R I students.

## D2M-R Quarter II Slides

~~*D2M-R II slides will be available in Spring 2026.*~~ D2M-R II will not be offered Spring 2026. Some materials may be published throughout the Spring and Summer. Others will not be available until Spring 2027. Refer to the course resources page for links to many excellent resources for learning plotting, analysis, and data reporting skills independently.